/* MS SQL */

CREATE TABLE Log
(
	id INT IDENTITY(1,1) NOT NULL PRIMARY KEY NONCLUSTERED,
	clientIP VARCHAR(15) NOT NULL,
	requestTime DATETIME NOT NULL,
	httpMethod VARCHAR(8) NOT NULL,
	path VARCHAR(2048) NOT NULL,
	status INT NOT NULL
);